### ISSUE TITLE
Execute lynx-docs export command twice for the YAML changes to reflect

### ISSUE THREAD

**Issue by danmork** [lynx-json/lynx-docs#60] opened 2017-08-11 16:07 UTC
Recording an issue reported via a private channel. The user claims that they must "execute lynx-docs export command twice for the YAML changes to reflect".

**Comment by ansongoldade** [comment] 2017-11-28 22:29
I am unable to reproduce this issue and have not seen any additional reports. Can we close this until we have reproduction steps?

**Comment by ansongoldade** [comment] 2017-11-28 22:42
We are unable to reproduce so we are closing until we have reproduction steps.

**Closed by ansongoldade** 2017-11-28 22:42 UTC
